[MolecularSearch]
ri_search_range = 35.0
rt_search_range = 1.0
correlation_threshold = 0.5
score_threshold = 0.0
ri_spacing = 200.0
ri_std = 3.0
ri_calibration_compound_names = [
    "Methyl Caprylate",
    "Methyl Caprate",
    "Methyl Pelargonate",
    "Methyl Laurate",
    "Methyl Myristate", 
    "Methyl Palmitate", 
    "Methyl Stearate", 
    "Methyl Eicosanoate", 
    "Methyl Docosanoate", 
    "Methyl Linocerate", 
    "Methyl Hexacosanoate", 
    "Methyl Octacosanoate", 
    "Methyl Triacontanoate",
]
exploratory_mode = false
score_methods = [ "highest_sim_score", "highest_ss",]
output_score_method = "All"

[GasChromatograph]
use_deconvolution = false
implemented_smooth_method = [ "savgol", "hanning", "blackman", "bartlett", "flat", "boxcar",]
smooth_window = 5
smooth_method = "savgol"
savgol_pol_order = 2
peak_derivative_threshold = 0.0005
peak_height_max_percent = 10.0
peak_max_prominence_percent = 1.0
min_peak_datapoints = 5.0
max_peak_width = 0.1
noise_threshold_method = "manual_relative_abundance"
noise_threshold_methods_implemented = [ "auto_relative_abundance", "manual_relative_abundance", "second_derivative",]
std_noise_threshold = 3
peak_height_min_percent = 0.1
peak_min_prominence_percent = 0.1
eic_signal_threshold = 0.01
max_rt_distance = 0.025
