file_paths = ["data/raw_data/Blanch_Nat_Lip_C_12_AB_M_17_NEG_25Jan18_Brandi-WCSH5801.raw"]
output_directory = "output"
corems_toml_path = "configuration/lipid_configs/emsl_lipidomics_corems_params.toml"
metabref_token_path = "metabref.token"
scan_translator_path = "configuration/lipid_configs/emsl_lipidomics_scan_translator.toml"
cores = 1