name: MiniWDL linter CI

on:
  push:
  workflow_dispatch:

jobs:
  run-miniwdl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # specify the Python version you need

    - name: Install MiniWDL
      run: |
        python -m pip install --upgrade pip
        pip install miniwdl

# TODO KRH: Add these back in once the WDL and docker images are ready
#    - name: Test LCMS Lipid MiniWDL
#      run: |
#        miniwdl run wdl/metaMS_lipidomics.wdl -i wdl/metams_input_lipidomics.json

    - name: Test GCMS MiniWDL
      run: |
        # Add the commands to run your MiniWDL workflow
        miniwdl run wdl/metaMS_gcms.wdl -i wdl/metams_input_gcms.json --verbose --no-cache --copy-input-files
  